# Generated by Django 4.2.16 on 2024-11-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_imagenproducto_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='info',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
